---
title: "ripper"
author: "Elena Romero Contreras"
date: "18 de febrero de 2019"
output: pdf_document
---

```{r}
# BIBLIOTECAS

source("preprocesado.r")

library(RWeka)
library(caret)
library(DMwR) 
library(bmrm)
# library(ggplot2)
# library(RKEEL)
# library(GGally)
# library(Hmisc)
# library(dplyr)
# library(corrplot)
# library(tidyr)
# library(VIM)
library(mice)
```

```{r}
train <- read.csv("train.csv", na.strings = c("?", "NA", "NR", "na", "NaN", "nan"))
train$C <- as.factor(train$C)
test <- read.csv("test.csv", na.strings = c("?", "NA", "NR", "na", "NaN", "nan"))


# FUNCIONES AUXILIARES

# Crea fichero con formato subida
createSubmission <- function(pred, filename){
  sub <- cbind(Id = 1:length(pred), Prediction = as.numeric(as.character(pred)))
  write.csv(sub, paste0("subs-ripper/",filename), row.names = F)
  sub
}

# Calcula el score de validación cruzada para el dataset
# funcion.train.predict: función(train, test) que entrena el clasificador con train y devuelve las predicciones sobre test
cross_validation <- function(dataset, funcion.train.predict, folds = 10){
  fold.indexes <- balanced.cv.fold(dataset$C)
  return(mean(sapply(1:folds, cross_validation_fold, fold.indexes, dataset, funcion.train.predict)))
}

cross_validation_fold <- function(fold, indexes, dataset, funcion.train.predict){
  train.inds <- which(indexes==fold)
  train <- dataset[train.inds,]
  test <- na.omit(dataset[-train.inds,])
  ypred <- funcion.train.predict(train, test[,-ncol(test)])
  mean(ypred==test$C)
}

# Resuelve problema desbalanceo
solveUnbalance <- function(data,type='ubOver'){
  n <- ncol(data)
  new.data <- ubBalance(data[,1:n-1], as.factor(data$C), type=type, positive=1)
  balanced <- cbind(new.data$X,C=new.data$Y)
  return (balanced)
}

# Comprueba si hay valores perdidos en cada fila
has.na <- function(x) apply(x,1,function(z)any(is.na(z)))
```

```{r}
#summary(train)
#summary(test)
```

```{r}
# SUBIDA 1
set.seed(123)


funcion.train.predict <- function(train, test){
  # Train
  model <- JRip(C ~ ., train)
  # Predict
  pred <- predict(model, test)
  return(pred)
}
```

```{r}
# SUBIDA 2
set.seed(123)

#Quitamos filas que toman el mismo valor -68000 y algo en muchas de sus variables -> sospechoso
#La mayoría de estas filas en train tienen etiqueta 0 -> asignamos 0 a filas en test con este valor

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  
  # Train
  model <- JRip(C ~ ., train[-outliers.train,])
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 
```

```{r}
# SUBIDA 3
set.seed(123)


# Quitamos filas con NAs en train

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  indices.nas.train <- which(has.na(train))
  
  # Train
  model <- JRip(C ~ ., train[-c(outliers.train, indices.nas.train),])
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 
```

```{r}
# SUBIDA 4
set.seed(123)


# Imputamos NAs en train

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  
  if(length(outliers.train) > 0){
    train <- train[-outliers.train,]
  }
  # Imputación NAs por media
  imputed <- mice(train, m=1, method = "mean")
  train <- complete(imputed)
  
  
  # Train
  model <- JRip(C ~ ., train)
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 
```

```{r}
# SUBIDA 5
set.seed(123)


# Imputamos NAs en train con KNN

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  
  if(length(outliers.train) > 0){
    train <- train[-outliers.train,]
  }
  # Imputación NAs con kNN
  train <- knnImputation(train) 

  # Train
  model <- JRip(C ~ ., train)
  
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 
  

# Validación cruzada
cross_validation(train, funcion.train.predict)

# Predicción test
sub.prueba <- funcion.train.predict(train, test)
sub <- createSubmission(sub.prueba, "test5") 
```

```{r}
# SUBIDA 6
set.seed(123)

# Subida 3 + quitamos atributos poco relacionados con la clase (<0.01)

  # Quitamos columnas menos correladas con la clase
 #train$C <- as.numeric(levels(train$C))[train$C]
 #abs(cor(train[-indices.nas.train,])[,ncol(train)])<0.01

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  indices.nas.train <- which(has.na(train))

  train <- train[,-c(41,44,31,48,1)]
  # Train
  model <- JRip(C ~ ., train[-c(outliers.train, indices.nas.train),])
  print(model)
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 
``` 

```{r}
# SUBIDA 7
set.seed(123)

# Subida 3 + quitamos atributos poco relacionados con la clase (<0.009)

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  indices.nas.train <- which(has.na(train))

  train <- train[,-c(41,44,31,48)]
  # Train
  model <- JRip(C ~ ., train[-c(outliers.train, indices.nas.train),])

  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 
```

```{r}
# SUBIDA 8
set.seed(123)

table(train$C)  # Desbalanceada

# Subida 3 + balanceo

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  indices.nas.train <- which(has.na(train))
  
  train <- train[-c(outliers.train, indices.nas.train),]
  balanced <- solveUnbalance(train, type="ubUnder")

  # Train
  model <- JRip(C ~ ., balanced)
  #print(model)
  
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 

# Validación cruzada
cross_validation(train, funcion.train.predict)
# Predicción test
sub.prueba <- funcion.train.predict(train, test)
sub <- createSubmission(sub.prueba, "test8") 
```



```{r}
# SUBIDA 9
set.seed(123)


# Subida 2 + imputación knn por clases

funcion.train.predict <- function(train, test){
  # Preprocesamiento
  outliers.train <- which(apply(train[,-ncol(train)], MARGIN=1, function(x) any(!is.na(x) & x < -68000)))
  outliers.test <- which(apply(test, MARGIN=1, function(x) any(!is.na(x) && x < -68000)))
  #indices.nas.train <- which(has.na(train))
  
  train <- train[-outliers.train,]
  
  train.completed.0 <- knnImputation(train[train$C == 0,]) 
  train.completed.1 <- knnImputation(train[train$C == 1,])
  train.completed <- rbind(train.completed.0, train.completed.1)
  
  # Training
  model <- JRip(C ~ ., train.completed)
  print(model)
  
  # Predict
  pred <- predict(model, test)
  pred[outliers.test] <- 0
  return(pred)
} 

# Validación cruzada
cross_validation(train, funcion.train.predict)
# Predicción test
sub.prueba <- funcion.train.predict(train, test)
sub <- createSubmission(sub.prueba, "test9") 
```

# Probar

* Imputación NAS: encadenado
* Discretización
* Filtros de ruido: EF por consenso, EF por mayoría, CVCF por consenso/mayoría, IPF por consenso/mayoría
* PCA?



# SUBIDAS

Subida | Fecha | Score train (CV) | Score test | Posición
-- | -- | -- | -- | --
1 | 18-02-2019 | 0.73758 | 0.88514  | 14
2 | 18-02-2019 | 0.73831 | 0.89076 | 10
3 | 18-02-2019 | 0.73831 | 0.89076 | 10
4 | 21-02-2019 | 0.74461 | 0.88514 | 11
5 | 23-02-2019 | 0.73908 | 0.87953 | 11
6 | 23-02-2019 | 0.74195 | 0.87850 | 11 
7 | 23-02-2019 | 0.73766 | 0.88055 | 11
8 | 23-02-2019 | 0.69460 | 0.85349 | 11
9 | 23-02-2019 | 0.74595 | 0.89688 | 7
